name: Build and Push BETA API Docker Image

on:
  push:
    branches:
      - beta

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API Docker image
        run: docker build -t ghcr.io/lyttle-development/community.v3.api:beta -f Api/Dockerfile .

      - name: Push API Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/lyttle-development/community.v3.api:beta
