name: BETA Workflow

on:
  push:
    branches:
      - beta

jobs:
  docker-build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API Docker image
        run: docker build -t ghcr.io/lyttle-development/community.v3.api:beta -f Api/Dockerfile .

      - name: Push API Docker image to GitHub Container Registry
        run: docker push ghcr.io/lyttle-development/community.v3.api:beta

      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_APP_NAME_API }}"
          token: "${{ secrets.CAPROVER_APP_TOKEN_API }}"
          image: "ghcr.io/lyttle-development/community.v3.api:beta"

  docker-build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Client Docker image
        run: docker build -t ghcr.io/lyttle-development/community.v3.client:beta -f Client/Dockerfile .

      - name: Push Client Docker image to GitHub Container Registry
        run: docker push ghcr.io/lyttle-development/community.v3.client:beta

      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_APP_NAME_CLIENT }}"
          token: "${{ secrets.CAPROVER_APP_TOKEN_CLIENT }}"
          image: "ghcr.io/lyttle-development/community.v3.client:beta"

  docker-build-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Dashboard Docker image
        run: docker build -t ghcr.io/lyttle-development/community.v3.dashboard:beta -f Dashboard/Dockerfile .

      - name: Push Dashboard Docker image to GitHub Container Registry
        run: docker push ghcr.io/lyttle-development/community.v3.dashboard:beta

      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_APP_NAME_DASHBOARD }}"
          token: "${{ secrets.CAPROVER_APP_TOKEN_DASHBOARD }}"
          image: "ghcr.io/lyttle-development/community.v3.dashboard:beta"
